### ISSUE TITLE
Check parameter distribution

### ISSUE THREAD

**Issue by miguelalba** [RakipInitiative/vocabularies#12]
From proposals for improving RAKIP harmonization resources:

> I think that it is rather difficult for an end user to identify the Parameter distribution. The number and meaning of distribution parameters may be provided in the controlled vocabulary instead of a reference to the ProbOnto report.MF: good suggestion. How to get this information into the CV?The suggestion from Stylianos is accepted including proposed ordering

Please check that the parameter distribution vocabulary at https://knime.bfr.berlin/vocabularies_frontend/frontend.html is correct according to the proposal.

**Comment by ganasp** [comment]
@esther-sundermann The decision regarding the controlled vocabulary for the parameter distribution was made in 2018. For me the parameter distribution vocabulary seems to be fine, but I'm not so familiar with that. Please, could you have also a look at this point.

**Comment by esther-sundermann** [comment]
Liebe Petra (@ganasp ),
wenn du sagst, dass für dich die Liste in Ordnung ist, dann ist das auch okay für mich.

Zur Erinnerung: In dem Kommentar wird vorgeschlagen die Arbeit des ProbOnto report als Grundlage zu nehmen und die daraus abgeleiteten Parameterverteilung und dazugehörige Referenzen findest du hier: https://docs.google.com/spreadsheets/d/1C6N4-YWX9OMmNStd2rYlSUaVys-aiJGLj00cD44aVc8/edit#gid=1730313417
