### ISSUE TITLE
Add "larva/50g" and "persons" to unit

### ISSUE THREAD

**Issue by miguelalba** [RakipInitiative/vocabularies#6]
Similar to #8. Proposal:

| Name | Comment | Category |
| - | - | - |
| larva/50g |  Larva per 50g | Mass ratio (4) |
| persons | Number of persons | Number (19) |

* The ids of the units are assigned unique and not relevant. They are not included in the table.
* The categories have their categories ids in parentheses.

**Comment by miguelalba** [comment]
To include proposal in DB.

**Comment by esther-sundermann** [comment]
I used the google sheet (https://docs.google.com/spreadsheets/d/1C6N4-YWX9OMmNStd2rYlSUaVys-aiJGLj00cD44aVc8/edit#gid=999493606) to look at availabel parameter categories. I am not 100% sure whether I understood all categries correctly (eg "Number Concentration Difference") and I am wondering about the meaning (am I right by saying that parametes of the category "arbitrary fractions" can NOT be transformed into each other, but parameters of the category "mass" can).

That being said:
- I think "number" is correct for "persons". 
- I think "larva/50g" is not a "mass ratio" but "Number Content (count/mass)"

**Comment by mfilter** [comment]
I agree. This fits better.
Re: "arbitrary fractions" can NOT be transformed into each other, but parameters of the category "mass" can): yes, that is right.
Thx

**Comment by esther-sundermann** [comment]
Thx @mfilter !

**Comment by miguelalba** [comment]
Closed with https://github.com/RakipInitiative/vocabularies/pull/13
